# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0002_add_synced_field'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('training_date', models.DateField(verbose_name='Date de formation')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='Nombre max de participants')),
                ('evaluation_criteria', models.JSONField(blank=True, default=dict, null=True, verbose_name="Critères d'évaluation")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='projects.project', verbose_name='Projet')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_given', to=settings.AUTH_USER_MODEL, verbose_name='Formateur')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('presence', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Retard'), ('partial', 'Partiel')], default='present', max_length=20, verbose_name='Presence')),
                ('attendance_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de presence')),
                ('evaluation_score', models.IntegerField(blank=True, null=True, verbose_name="Score d'évaluation")),
                ('evaluation_notes', models.TextField(blank=True, null=True, verbose_name="Notes d'évaluation")),
                ('signature_uri', models.CharField(blank=True, max_length=500, null=True, verbose_name='Signature')),
                ('photos', models.JSONField(blank=True, default=list, null=True, verbose_name='Photos')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendances', to='producers.producer', verbose_name='Producteur')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='trainings.training', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Presence à formation',
                'verbose_name_plural': 'Presences à formation',
                'ordering': ['-training__training_date'],
                'unique_together': {('training', 'producer')},
            },
        ),
    ]
