# Generated by Django 5.2.14 on 2026-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Superviseur'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=10, verbose_name='Plateforme'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Rejete')], default='approved', max_length=20, verbose_name='Statut d inscription'),
        ),
    ]
