# Generated by Django 5.2.14 on 2026-05-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('producers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine'), ('certification', 'Certification'), ('quality', 'Controle qualite'), ('phytosanitary', 'Phytosanitaire'), ('traceability', 'Tracabilite'), ('follow_up', 'Suivi')], max_length=20, verbose_name='Type inspection')),
                ('checklist_template', models.JSONField(default=list, verbose_name='Modele checklist')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Modele inspection',
                'verbose_name_plural': 'Modeles inspection',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code inspection')),
                ('inspection_type', models.CharField(choices=[('routine', 'Routine'), ('certification', 'Certification'), ('quality', 'Controle qualite'), ('phytosanitary', 'Phytosanitaire'), ('traceability', 'Tracabilite'), ('follow_up', 'Suivi')], default='routine', max_length=20, verbose_name='Type inspection')),
                ('planned_date', models.DateField(verbose_name='Date prevue')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('status', models.CharField(choices=[('planned', 'Planifie'), ('in_progress', 'En cours'), ('completed', 'Termine'), ('cancelled', 'Annule')], default='planned', max_length=20, verbose_name='Statut')),
                ('result', models.CharField(choices=[('passed', 'Conforme'), ('failed', 'Non conforme'), ('conditional', 'Conditionnel'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Resultat')),
                ('score_overall', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score global')),
                ('score_cultivation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score culture')),
                ('score_processing', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score transformation')),
                ('score_storage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score stockage')),
                ('score_traceability', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score tracabilite')),
                ('score_environment', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score environnement')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Recommandations')),
                ('non_conformities', models.TextField(blank=True, null=True, verbose_name='Non-conformites')),
                ('corrective_actions', models.TextField(blank=True, null=True, verbose_name='Actions correctives')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='Suivi requis')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Date suivi')),
                ('follow_up_notes', models.TextField(blank=True, null=True, verbose_name='Notes suivi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspections/photos/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Inspecteur')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='parcels.parcel', verbose_name='Parcelle')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='producers.producer', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('category', models.CharField(max_length=100, verbose_name='Categorie')),
                ('item', models.CharField(max_length=500, verbose_name='Element')),
                ('is_compliant', models.BooleanField(default=False, verbose_name='Conforme')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='inspections.inspection', verbose_name='Inspection')),
            ],
            options={
                'verbose_name': 'Element checklist',
                'verbose_name_plural': 'Elements checklist',
                'ordering': ['category', 'item'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('photo', models.ImageField(upload_to='inspections/gallery/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legende')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categorie')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection', verbose_name='Inspection')),
            ],
            options={
                'verbose_name': 'Photo inspection',
                'verbose_name_plural': 'Photos inspection',
                'ordering': ['-created_at'],
            },
        ),
    ]
