# Generated by Django 5.2.14 on 2026-06-05 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('producers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgriculturalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('recommendation_type', models.CharField(choices=[('yield', 'Amelioration rendement'), ('cultural', 'Pratique culturale'), ('pest', 'Lutte antiparasitaire'), ('weather', 'Conseil meteorologique'), ('market', 'Conseil marche'), ('general', 'Conseil general')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorite')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Donnees')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_applied', models.BooleanField(default=False, verbose_name='Applique')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='parcels.parcel', verbose_name='Parcelle')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='producers.producer', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Recommandation agricole',
                'verbose_name_plural': 'Recommandations agricoles',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('endpoint', models.CharField(max_length=100, verbose_name='Endpoint')),
                ('prompt', models.TextField(verbose_name='Prompt')),
                ('response', models.TextField(blank=True, verbose_name='Reponse')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens utilises')),
                ('processing_time', models.FloatField(default=0, verbose_name='Temps traitement (s)')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Succes')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log IA',
                'verbose_name_plural': 'Logs IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('topic', models.CharField(choices=[('general', 'General'), ('production', 'Production'), ('parcel', 'Parcelle'), ('inspection', 'Inspection'), ('harmless', 'Conseil agricole'), ('report', 'Rapport')], default='general', max_length=30, verbose_name='Sujet')),
                ('context_data', models.JSONField(blank=True, null=True, verbose_name='Donnees contextuelles')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session de chat',
                'verbose_name_plural': 'Sessions de chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant'), ('system', 'Systeme')], max_length=20, verbose_name='Role')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadonnees')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Message de chat',
                'verbose_name_plural': 'Messages de chat',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('report_type', models.CharField(choices=[('producers', 'Producteurs'), ('parcels', 'Parcelles'), ('productions', 'Productions'), ('inspections', 'Inspections'), ('global', 'Global'), ('region', 'Region')], max_length=30, verbose_name='Type')),
                ('period_start', models.DateField(verbose_name='Debut periode')),
                ('period_end', models.DateField(verbose_name='Fin periode')),
                ('summary', models.TextField(blank=True, verbose_name='Resume')),
                ('report_data', models.JSONField(blank=True, null=True, verbose_name='Donnees')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Fichier')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('generating', 'En generation'), ('completed', 'Termine'), ('failed', 'Echec')], default='pending', max_length=20, verbose_name='Statut')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='Genere par')),
            ],
            options={
                'verbose_name': 'Rapport mensuel',
                'verbose_name_plural': 'Rapports mensuels',
                'ordering': ['-period_start'],
            },
        ),
    ]
