# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0002_add_synced_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('donor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bailleur')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget')),
                ('start_date', models.DateField(verbose_name='Date de debut')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('intervention_zone', models.JSONField(blank=True, default=dict, null=True, verbose_name="Zone d'intervention")),
                ('objectives', models.JSONField(blank=True, default=dict, null=True, verbose_name='Objectifs')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('completed', 'Termine'), ('suspended', 'Suspendu'), ('cancelled', 'Annule')], default='draft', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Gere par')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('beneficiary_type', models.CharField(choices=[('producer', 'Producteur'), ('household', 'Menage'), ('group', 'Groupe'), ('other', 'Autre')], max_length=20, verbose_name='Type de beneficiaire')),
                ('household_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du menage')),
                ('household_size', models.IntegerField(blank=True, null=True, verbose_name='Taille du menage')),
                ('enrollment_date', models.DateField(verbose_name="Date d'inscription")),
                ('indicators_reached', models.JSONField(blank=True, default=dict, null=True, verbose_name='Indicateurs atteints')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_beneficiaries', to='producers.producer', verbose_name='Producteur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Beneficiaire',
                'verbose_name_plural': 'Beneficiaires',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('activity_type', models.CharField(choices=[('training', 'Formation'), ('distribution', 'Distribution'), ('sensitization', 'Sensibilisation'), ('follow_up', 'Suivi technique'), ('other', 'Autre')], max_length=20, verbose_name="Type d'activité")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('planned_date', models.DateField(verbose_name='Date prevue')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Date reelle')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('target_audience', models.CharField(blank=True, max_length=200, null=True, verbose_name='Public cible')),
                ('participants_count', models.IntegerField(blank=True, null=True, verbose_name='Nombre de participants')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget')),
                ('status', models.CharField(default='planned', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Activite de projet',
                'verbose_name_plural': 'Activites de projet',
                'ordering': ['-planned_date'],
            },
        ),
    ]
