# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('step_type', models.CharField(choices=[('approval', 'Approbation'), ('review', 'Revue'), ('validation', 'Validation'), ('notification', 'Notification')], max_length=20, verbose_name='Type')),
                ('order', models.IntegerField(verbose_name='Ordre')),
                ('required_role', models.CharField(choices=[('agent', 'Agent'), ('chef_zone', 'Chef de zone'), ('supervisor', 'Superviseur'), ('admin', 'Administrateur')], max_length=30, verbose_name='Role requis')),
                ('auto_approve', models.BooleanField(default=False, verbose_name='Approbation automatique')),
                ('timeout_hours', models.IntegerField(blank=True, null=True, verbose_name='Delai (heures)')),
                ('escalation_role', models.CharField(blank=True, max_length=30, null=True, verbose_name="Role d'escalade")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Etape de workflow',
                'verbose_name_plural': 'Etapes de workflow',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('approved', 'Approuve'), ('rejected', 'Rejete'), ('cancelled', 'Annule')], default='pending', max_length=20, verbose_name='Statut')),
                ('current_step', models.IntegerField(default=0, verbose_name='Etape actuelle')),
                ('entity_type', models.CharField(max_length=50, verbose_name="Type d'entité")),
                ('entity_id', models.IntegerField(verbose_name='ID entité')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('action', models.CharField(blank=True, max_length=50, null=True, verbose_name='Action')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Termine le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Assigne a')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Initie par')),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowstep', verbose_name='Etape')),
            ],
            options={
                'verbose_name': 'Instance de workflow',
                'verbose_name_plural': 'Instances de workflow',
                'ordering': ['-created_at'],
            },
        ),
    ]
