# Generated by Django 5.2.14 on 2026-06-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('variety', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variété')),
                ('culture_type', models.CharField(choices=[('cash', 'Culture de rente'), ('food', 'Culture vivrière'), ('vegetable', 'Maraîchère'), ('fruit', 'Fruitière'), ('other', 'Autre')], default='cash', max_length=20, verbose_name='Type de culture')),
                ('growth_duration_days', models.IntegerField(blank=True, null=True, verbose_name='Durée de production (jours)')),
                ('average_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendement moyen')),
                ('yield_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unité de rendement')),
                ('ideal_season', models.CharField(blank=True, max_length=50, null=True, verbose_name='Saison idéale')),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix moyen du marché')),
                ('price_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unité de prix')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'ordering': ['name'],
            },
        ),
    ]
