# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('producers', '0002_add_synced_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('product', models.CharField(max_length=200, verbose_name='Produit')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('quantity_unit', models.CharField(default='kg', max_length=20, verbose_name='Unité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix total')),
                ('quality_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prime qualité')),
                ('buyer', models.CharField(max_length=200, verbose_name='Acheteur')),
                ('collection_center', models.CharField(blank=True, max_length=200, null=True, verbose_name='Centre de collecte')),
                ('delivery_date', models.DateField(verbose_name='Date de livraison')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('delivered', 'Livree'), ('cancelled', 'Annulee')], default='pending', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('synced', models.BooleanField(default=True, verbose_name='Synchronisé')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='campaigns.campaign', verbose_name='Campagne')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='producers.producer', verbose_name='Producteur')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
