# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0002_add_synced_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('validity_period_months', models.IntegerField(blank=True, null=True, verbose_name='Duree de validite (mois)')),
                ('audit_required', models.BooleanField(default=True, verbose_name='Audit requis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de certification',
                'verbose_name_plural': 'Types de certifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProducerCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('certified', 'Certifie'), ('expired', 'Expiree'), ('revoked', 'Revoquee')], default='pending', max_length=20, verbose_name='Statut')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de certificat')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Date de delivrance')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('last_audit_date', models.DateField(blank=True, null=True, verbose_name='Dernier audit')),
                ('next_audit_date', models.DateField(blank=True, null=True, verbose_name='Prochain audit')),
                ('audit_notes', models.TextField(blank=True, null=True, verbose_name="Notes d'audit")),
                ('document', models.FileField(blank=True, null=True, upload_to='certifications/', verbose_name='Document')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_certifications', to='certifications.certificationtype', verbose_name='Type de certification')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certifications', to=settings.AUTH_USER_MODEL, verbose_name='Delivre par')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='producers.producer', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Certification producteur',
                'verbose_name_plural': 'Certifications producteurs',
                'ordering': ['-issue_date'],
            },
        ),
    ]
