# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('task_type', models.CharField(choices=[('inspection', 'Inspection'), ('training', 'Formation'), ('survey', 'Enquête'), ('visit', 'Visite'), ('other', 'Autre')], max_length=20, verbose_name='Type de tâche')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('pending', 'A faire'), ('in_progress', 'En cours'), ('completed', 'Terminee'), ('cancelled', 'Annulee')], default='pending', max_length=20, verbose_name='Statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'echeance")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Termine le')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigne a')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
            ],
            options={
                'verbose_name': 'Tache',
                'verbose_name_plural': 'Taches',
                'ordering': ['-due_date', '-priority'],
            },
        ),
    ]
