# Generated by Django 5.2.14 on 2026-05-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('president', models.CharField(blank=True, max_length=200, null=True, verbose_name='President')),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero enregistrement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cooperatives', to='core.commune', verbose_name='Commune')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cooperatives', to='core.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Cooperative',
                'verbose_name_plural': 'Cooperatives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code producteur')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True, verbose_name='Genre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('cin', models.CharField(blank=True, max_length=50, null=True, verbose_name='CIN')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Certifie')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Date de certification')),
                ('certification_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de certification')),
                ('certification_expiry', models.DateField(blank=True, null=True, verbose_name='Expiration certification')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='producers/photos/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='core.commune', verbose_name='Commune')),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='producers.cooperative', verbose_name='Cooperative')),
                ('fokontany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='core.fokontany', verbose_name='Fokontany')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producers', to='core.region', verbose_name='Region')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_producers', to=settings.AUTH_USER_MODEL, verbose_name='Enregistre par')),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
