# Generated by Django 5.2.14 on 2026-06-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='synced',
            field=models.BooleanField(default=True, verbose_name='Synchronise'),
        ),
    ]
