# Generated by Django 5.2.14 on 2026-08-17 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_producer_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('photo', models.ImageField(upload_to='producers/gallery/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legende')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de prise')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='producers.producer', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Photo de producteur',
                'verbose_name_plural': 'Photos de producteurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
