# Generated by Django 5.2.14 on 2026-08-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_producerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='eu_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Statut UE'),
        ),
        migrations.AddField(
            model_name='producer',
            name='identified_risks',
            field=models.TextField(blank=True, null=True, verbose_name='Risques identifiés'),
        ),
        migrations.AddField(
            model_name='producer',
            name='internal_inspector_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Inspecteur SCI'),
        ),
        migrations.AddField(
            model_name='producer',
            name='joined_at',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'intégration"),
        ),
        migrations.AddField(
            model_name='producer',
            name='last_external_inspection_at',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière inspection externe'),
        ),
        migrations.AddField(
            model_name='producer',
            name='last_internal_inspection_at',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière inspection interne'),
        ),
        migrations.AddField(
            model_name='producer',
            name='member_processing',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Préparation/transformation'),
        ),
        migrations.AddField(
            model_name='producer',
            name='nop_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Statut NOP'),
        ),
        migrations.AddField(
            model_name='producer',
            name='processing_activities',
            field=models.TextField(blank=True, null=True, verbose_name='Activités de préparation'),
        ),
        migrations.AddField(
            model_name='producer',
            name='risk_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie de risque'),
        ),
    ]
