# Generated by Django 5.2.14 on 2026-08-23 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0005_producer_eu_status_producer_identified_risks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='certification_date',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='certification_expiry',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='certification_number',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='is_certified',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='phone_secondary',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='photo',
        ),
        migrations.AddField(
            model_name='producer',
            name='exclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date de l'exclusion"),
        ),
        migrations.AddField(
            model_name='producer',
            name='exclusion_reason',
            field=models.TextField(blank=True, null=True, verbose_name="Raison de l'exclusion"),
        ),
        migrations.AddField(
            model_name='producer',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom du membre'),
        ),
        migrations.AddField(
            model_name='producer',
            name='last_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom du membre'),
        ),
        migrations.AddField(
            model_name='producer',
            name='unit_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'unité de production"),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='president',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Président'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro enregistrement'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='eu_status',
            field=models.CharField(blank=True, choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('withdrawn', 'Retiré'), ('abandoned', 'Abandonné')], max_length=20, null=True, verbose_name='Statut UE'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='joined_at',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'intgration"),
        ),
        migrations.AlterField(
            model_name='producer',
            name='last_external_inspection_at',
            field=models.DateField(blank=True, null=True, verbose_name='Dernière inspection ECOCERT'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='member_processing',
            field=models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non')], max_length=10, null=True, verbose_name='Préparation ou transformation simple'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='nop_status',
            field=models.CharField(blank=True, choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('abandoned', 'Abandonné')], max_length=20, null=True, verbose_name='Statut NOP'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_producers', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='risk_category',
            field=models.CharField(blank=True, choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Fort')], max_length=20, null=True, verbose_name='Catégorie de risque'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut système'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='synced',
            field=models.BooleanField(default=True, verbose_name='Synchronisé'),
        ),
        migrations.AlterField(
            model_name='producerphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Légende'),
        ),
    ]
