# Generated by Django 5.2.14 on 2026-05-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('producers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code parcelle')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom/Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Altitude (m)')),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Precision GPS (m)')),
                ('polygon_coordinates', models.TextField(blank=True, null=True, verbose_name='Coordonnees polygone (GeoJSON)')),
                ('area', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Superficie (ha)')),
                ('vanilla_plants', models.PositiveIntegerField(default=0, verbose_name='Nombre de pieds de vanille')),
                ('productive_plants', models.PositiveIntegerField(default=0, verbose_name='Pieds productifs')),
                ('soil_type', models.CharField(blank=True, choices=[('clay', 'Argileux'), ('sandy', 'Sableux'), ('loamy', 'Limoneux'), ('volcanic', 'Volcanique'), ('mixed', 'Mixte')], max_length=20, null=True, verbose_name='Type de sol')),
                ('shade_percentage', models.PositiveIntegerField(default=0, verbose_name='Pourcentage ombrage')),
                ('irrigation', models.BooleanField(default=False, verbose_name='Irrigation')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='Date de plantation')),
                ('first_harvest_date', models.DateField(blank=True, null=True, verbose_name='Premiere recolte')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('fallow', 'En jachere'), ('new', 'Nouveau')], default='new', max_length=20, verbose_name='Statut')),
                ('is_certified', models.BooleanField(default=False, verbose_name='Certifie')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Date certification')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parcels/photos/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='producers.producer', verbose_name='Producteur')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_parcels', to=settings.AUTH_USER_MODEL, verbose_name='Enregistre par')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='core.vanillavariety', verbose_name='Variete')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('photo', models.ImageField(upload_to='parcels/gallery/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Legende')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de prise')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parcels.parcel', verbose_name='Parcelle')),
            ],
            options={
                'verbose_name': 'Photo de parcelle',
                'verbose_name_plural': 'Photos de parcelles',
                'ordering': ['-created_at'],
            },
        ),
    ]
