# Generated by Django 5.2.14 on 2026-06-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='synced',
            field=models.BooleanField(default=True, verbose_name='Synchronise'),
        ),
    ]
