# Generated by Django 5.2.14 on 2026-08-23 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_district'),
        ('parcels', '0002_parcel_synced'),
        ('producers', '0005_producer_eu_status_producer_identified_risks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='actual_harvest',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Récolte effective (kg)'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='conversion_level',
            field=models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3')], max_length=2, null=True, verbose_name='Niveau de conversion'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='conversion_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Début de conversion'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='conversion_status',
            field=models.CharField(blank=True, choices=[('organic', 'Biologique'), ('conversion', 'En conversion'), ('conventional', 'Conventionnelle')], max_length=20, null=True, verbose_name='Statut de conversion'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivered_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité livrée (kg)'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='estimated_yield',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Rendement estimé (kg/ha)'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='eu_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Statut UE'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='intercrop',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Interculture'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='main_crop',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Culture principale'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='nop_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Statut NOP'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Code parcelle'),
        ),
        migrations.AddConstraint(
            model_name='parcel',
            constraint=models.UniqueConstraint(fields=('producer', 'code'), name='unique_parcel_code_per_producer'),
        ),
    ]
