# Generated by Django 5.2.14 on 2026-08-23 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_parcel_actual_harvest_parcel_conversion_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelRegisterHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('period', models.CharField(choices=[('current', 'Année en cours'), ('previous', 'Récolte N-1')], max_length=10)),
                ('crop_slot', models.CharField(choices=[('main', 'Culture principale'), ('intercrop_1', 'Interculture / rotation 1'), ('intercrop_2', 'Interculture / rotation 2')], max_length=15)),
                ('estimated_yield', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Rendement estimé (kg/ha)')),
                ('actual_harvest', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Récolte effective (kg)')),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Rendement effectif (kg/ha)')),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité livrée (kg)')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_harvests', to='parcels.parcel')),
            ],
            options={
                'verbose_name': 'Relevé récolte du registre',
                'verbose_name_plural': 'Relevés récolte du registre',
                'constraints': [models.UniqueConstraint(fields=('parcel', 'period', 'crop_slot'), name='unique_register_harvest_slot')],
            },
        ),
    ]
