# Generated by Django 5.2.14 on 2026-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcelregisterharvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='bio_location',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Localisation bio'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='last_used_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de dernière utilisation'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'enregistrement"),
        ),
    ]
