# Generated by Django 5.2.14 on 2026-06-18 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_season_target_weight'),
        ('cultures', '0001_initial'),
        ('producers', '0002_add_synced_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de debut')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('objectives', models.JSONField(blank=True, default=dict, null=True, verbose_name='Objectifs de production')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminee'), ('pending', 'En attente'), ('cancelled', 'Annulee')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='cultures.culture', verbose_name='Culture')),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Gere par')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='campaigns.campaign', verbose_name='Campagne')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='producers.producer', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Producteur de campagne',
                'verbose_name_plural': 'Producteurs de campagne',
                'ordering': ['-enrollment_date'],
                'unique_together': {('campaign', 'producer')},
            },
        ),
    ]
