# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('producers', '0002_add_synced_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('type', models.CharField(choices=[('income', 'Revenu'), ('expense', 'Depense'), ('subvention', 'Subvention'), ('credit', 'Credit'), ('remboursement', 'Remboursement')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de transaction',
                'verbose_name_plural': 'Types de transaction',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('currency', models.CharField(default='MGA', max_length=3, verbose_name='Devise')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('transaction_date', models.DateField(verbose_name='Date de transaction')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('synced', models.BooleanField(default=True, verbose_name='Synchronisé')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='campaigns.campaign', verbose_name='Campagne')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='producers.producer', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Transaction financière',
                'verbose_name_plural': 'Transactions financières',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
