# Generated by Django 5.2.14 on 2026-05-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code production')),
                ('harvest_date', models.DateField(verbose_name='Date de recolte')),
                ('harvest_time', models.TimeField(blank=True, null=True, verbose_name='Heure de recolte')),
                ('weight_green', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Poids vert (kg)')),
                ('weight_prepared', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Poids prepare (kg)')),
                ('pods_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de gousses')),
                ('pods_grade_a', models.PositiveIntegerField(default=0, verbose_name='Gousses Grade A')),
                ('pods_grade_b', models.PositiveIntegerField(default=0, verbose_name='Gousses Grade B')),
                ('pods_grade_c', models.PositiveIntegerField(default=0, verbose_name='Gousses Grade C')),
                ('pods_rejected', models.PositiveIntegerField(default=0, verbose_name='Gousses rejetees')),
                ('vanillin_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de vanilline (%)')),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux humidite (%)')),
                ('status', models.CharField(choices=[('harvested', 'Recolte'), ('drying', 'Sechage'), ('curing', 'Affinage'), ('ready', 'Pret'), ('sold', 'Vendu')], default='harvested', max_length=20, verbose_name='Statut')),
                ('drying_start_date', models.DateField(blank=True, null=True, verbose_name='Debut sechage')),
                ('drying_end_date', models.DateField(blank=True, null=True, verbose_name='Fin sechage')),
                ('curing_start_date', models.DateField(blank=True, null=True, verbose_name='Debut affinage')),
                ('curing_end_date', models.DateField(blank=True, null=True, verbose_name='Fin affinage')),
                ('sale_date', models.DateField(blank=True, null=True, verbose_name='Date de vente')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix de vente (Ar)')),
                ('buyer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Acheteur')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='productions/photos/', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='parcels.parcel', verbose_name='Parcelle')),
                ('quality_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='core.qualitygrade', verbose_name='Grade de qualite')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_productions', to=settings.AUTH_USER_MODEL, verbose_name='Enregistre par')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='core.season', verbose_name='Saison')),
            ],
            options={
                'verbose_name': 'Production',
                'verbose_name_plural': 'Productions',
                'ordering': ['-harvest_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code lot')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du lot')),
                ('total_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Poids total (kg)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('productions', models.ManyToManyField(related_name='batches', to='productions.production', verbose_name='Productions')),
                ('quality_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.qualitygrade', verbose_name='Grade qualite')),
            ],
            options={
                'verbose_name': 'Lot de production',
                'verbose_name_plural': 'Lots de production',
                'ordering': ['-created_at'],
            },
        ),
    ]
