# Generated by Django 5.2.15 on 2026-07-07 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export'), ('SYNC', 'Synchronisation')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Élément')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID élément')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-timestamp'],
            },
        ),
    ]
