# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('producers', '0002_add_synced_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('type', models.CharField(choices=[('fertilizer', 'Engrais'), ('seed', 'Semences'), ('pesticide', 'Pesticides'), ('tool', 'Outils'), ('plant', 'Plants'), ('other', 'Autre')], max_length=20, verbose_name='Type')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'intrant",
                'verbose_name_plural': "Types d'intrants",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InputDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(max_length=20, verbose_name='Unité')),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur unitaire')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur totale')),
                ('distribution_date', models.DateField(verbose_name='Date de distribution')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('synced', models.BooleanField(default=True, verbose_name='Synchronisé')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_distributions', to='campaigns.campaign', verbose_name='Campagne')),
                ('distributed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Distribué par')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_distributions', to='producers.producer', verbose_name='Producteur')),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='inputs.inputtype', verbose_name="Type d'intrant")),
            ],
            options={
                'verbose_name': "Distribution d'intrant",
                'verbose_name_plural': "Distributions d'intrants",
                'ordering': ['-distribution_date'],
            },
        ),
    ]
