# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producers', '0002_add_synced_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('document_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('contract', 'Contrat'), ('certificate', 'Certificat'), ('attestation', 'Attestation'), ('land_title', 'Document foncier'), ('other', 'Autre')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('required', models.BooleanField(default=False, verbose_name='Requis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('file', models.FileField(upload_to='documents/producers/', verbose_name='Fichier')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name="Date d'emission")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('synced', models.BooleanField(default=True, verbose_name='Synchronisé')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='producers.producer', verbose_name='Producteur')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Telecharge par')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-issue_date'],
            },
        ),
    ]
