# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0002_parcel_synced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('category', models.CharField(choices=[('fungal', 'Fongique'), ('bacterial', 'Bacterienne'), ('viral', 'Virale'), ('pest', 'Parasite'), ('other', 'Autre')], max_length=20, verbose_name='Categorie')),
                ('affected_crops', models.JSONField(blank=True, default=list, null=True, verbose_name='Cultures affectees')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Symptômes')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Eleve'), ('critical', 'Critique')], default='medium', max_length=20, verbose_name='Gravite')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Traitement')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='Prevention')),
                ('photo_examples', models.JSONField(blank=True, default=list, null=True, verbose_name='Exemples de photos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Maladie/Parasite',
                'verbose_name_plural': 'Maladies/Parasites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhytosanitaryTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('treatment_type', models.CharField(choices=[('preventive', 'Preventif'), ('curative', 'Curatif'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='Type de traitement')),
                ('product_used', models.CharField(max_length=200, verbose_name='Produit utilise')),
                ('application_rate', models.CharField(blank=True, max_length=100, null=True, verbose_name="Dose d'application")),
                ('application_date', models.DateField(verbose_name="Date d'application")),
                ('severity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gravite avant traitement')),
                ('result', models.CharField(blank=True, choices=[('effective', 'Efficace'), ('partial', 'Partiel'), ('ineffective', 'Inefficace')], max_length=20, null=True, verbose_name='Resultat')),
                ('photos', models.JSONField(blank=True, default=list, null=True, verbose_name='Photos')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('synced', models.BooleanField(default=True, verbose_name='Synchronise')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments_applied', to=settings.AUTH_USER_MODEL, verbose_name='Applique par')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='phytosanitary.disease', verbose_name='Maladie')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='parcels.parcel', verbose_name='Parcelle')),
            ],
            options={
                'verbose_name': 'Traitement phytosanitaire',
                'verbose_name_plural': 'Traitements phytosanitaires',
                'ordering': ['-application_date'],
            },
        ),
    ]
