# Generated by Django 5.2.15 on 2026-07-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CINScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=200, verbose_name='Prénom(s)')),
                ('numero_cin', models.CharField(max_length=50, verbose_name='Numéro CIN')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, verbose_name='Sexe')),
                ('pere', models.CharField(blank=True, max_length=200, verbose_name='Père')),
                ('mere', models.CharField(blank=True, max_length=200, verbose_name='Mère')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('arrondissement', models.CharField(blank=True, max_length=200, verbose_name='Arrondissement')),
                ('date_delivrance', models.DateField(blank=True, null=True, verbose_name='Date de délivrance')),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('confidence', models.JSONField(blank=True, default=dict, verbose_name='Scores de confiance')),
                ('corrected_fields', models.JSONField(blank=True, default=list, verbose_name='Champs corrigés')),
                ('scan_metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées du scan')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge calculé')),
                ('source', models.CharField(choices=[('auto', 'Lecture automatique'), ('manual', 'Saisie manuelle')], default='auto', max_length=10, verbose_name='Source')),
                ('photo_recto', models.ImageField(blank=True, null=True, upload_to='cin/recto/')),
                ('photo_verso', models.ImageField(blank=True, null=True, upload_to='cin/verso/')),
                ('photo_recto_enhanced', models.ImageField(blank=True, null=True, upload_to='cin/recto_enhanced/')),
                ('photo_verso_enhanced', models.ImageField(blank=True, null=True, upload_to='cin/verso_enhanced/')),
                ('photo_beneficiaire', models.ImageField(blank=True, null=True, upload_to='cin/beneficiaire/')),
                ('synced', models.BooleanField(default=False, verbose_name='Synchronisé')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cin_scans', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Scan CIN',
                'verbose_name_plural': 'Scans CIN',
                'ordering': ['-created_at'],
            },
        ),
    ]
