# Generated by Django 5.2.14 on 2026-06-18 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Station meteo',
                'verbose_name_plural': 'Stations meteo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('alert_type', models.CharField(choices=[('rain', 'Pluie'), ('storm', 'Tempête'), ('drought', 'Secheresse'), ('heat', 'Chaleur'), ('frost', 'Gel'), ('other', 'Autre')], max_length=20, verbose_name="Type d'alerte")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('forecast_start', models.DateTimeField(verbose_name='Debut prevu')),
                ('forecast_end', models.DateTimeField(verbose_name='Fin prevue')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Envoyé')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('weather_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='weather.weatherstation', verbose_name='Station meteo')),
            ],
            options={
                'verbose_name': 'Alerte meteo',
                'verbose_name_plural': 'Alertes meteo',
                'ordering': ['-forecast_start'],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('recorded_at', models.DateTimeField(verbose_name='Enregistre le')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (C)')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Humidite (%)')),
                ('rainfall', models.FloatField(blank=True, null=True, verbose_name='Pluie (mm)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Vitesse du vent (km/h)')),
                ('wind_direction', models.CharField(blank=True, max_length=10, null=True, verbose_name='Direction du vent')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Pression (hPa)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='weather.weatherstation', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'Releve meteo',
                'verbose_name_plural': 'Releves meteo',
                'ordering': ['-recorded_at'],
                'unique_together': {('station', 'recorded_at')},
            },
        ),
    ]
