# Generated by Django 5.2.14 on 2026-05-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QualityGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('min_vanillin_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux de vanilline minimum (%)')),
                ('min_moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux humidite minimum (%)')),
                ('max_moisture_content', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taux humidite maximum (%)')),
                ('price_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Facteur de prix')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Grade de qualite',
                'verbose_name_plural': 'Grades de qualite',
                'ordering': ['-price_factor'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VanillaVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Variete de vanille',
                'verbose_name_plural': 'Varietes de vanille',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Fokontany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fokontanys', to='core.commune', verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'Fokontany',
                'verbose_name_plural': 'Fokontanys',
                'ordering': ['commune', 'name'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='core.region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('year', models.PositiveIntegerField(verbose_name='Annee')),
                ('start_date', models.DateField(verbose_name='Date de debut')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='Saison en cours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'ordering': ['-year', '-start_date'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('syncing', 'En cours'), ('completed', 'Termine'), ('failed', 'Echoue')], default='pending', max_length=20, verbose_name='Statut')),
                ('records_sent', models.PositiveIntegerField(default=0, verbose_name='Enregistrements envoyes')),
                ('records_received', models.PositiveIntegerField(default=0, verbose_name='Enregistrements recus')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Debut')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Message erreur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Journal de synchronisation',
                'verbose_name_plural': 'Journaux de synchronisation',
                'ordering': ['-started_at'],
            },
        ),
    ]
