# Generated by Django 5.2.14 on 2026-08-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'unite")),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code unite')),
                ('unit_type', models.CharField(choices=[('group', 'Groupe'), ('site', 'Site'), ('village', 'Village'), ('region', 'Region')], default='group', max_length=20, verbose_name="Type d'unite")),
                ('manager_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsable')),
                ('manager_function', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fonction du responsable')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('members_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de membres')),
                ('total_area', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Superficie totale (ha)')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Date de creation')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu')], default='active', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_units', to='core.commune', verbose_name='Commune')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_units', to='core.district', verbose_name='District')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_units', to='core.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Unite de production',
                'verbose_name_plural': 'Unites de production',
                'ordering': ['name'],
            },
        ),
    ]
